// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSiA0hmEJ_mfGDn7XvsCXPWpANuXNW-SM',
    appId: '1:469536908550:web:506711ea71905bbb9faa87',
    messagingSenderId: '469536908550',
    projectId: 'fruites-12230',
    authDomain: 'fruites-12230.firebaseapp.com',
    storageBucket: 'fruites-12230.firebasestorage.app',
    measurementId: 'G-ZLRJ02QFDV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRiF53lwZe74GU6gNgVPoftuq8uz3oeA',
    appId: '1:469536908550:android:0c95456a3a6d30219faa87',
    messagingSenderId: '469536908550',
    projectId: 'fruites-12230',
    storageBucket: 'fruites-12230.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSiA0hmEJ_mfGDn7XvsCXPWpANuXNW-SM',
    appId: '1:469536908550:web:a8281ec948dd7f1a9faa87',
    messagingSenderId: '469536908550',
    projectId: 'fruites-12230',
    authDomain: 'fruites-12230.firebaseapp.com',
    storageBucket: 'fruites-12230.firebasestorage.app',
    measurementId: 'G-8WHQZJ07HY',
  );

}